services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm start
    volumes:
      - ./app:/app

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./services/caddy/caddy_data:/data
      - ./services/caddy/caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
