version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: legacy72/devops-for-programmers-project-74:latest
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: