services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm run dev
    volumes:
      - ./app:/app
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - DATABASE_NAME=hexlet_devops
      - DATABASE_USERNAME=hexlet_devops
      - DATABASE_PASSWORD=hexlet_devops
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./services/caddy/caddy_data:/data
      - ./services/caddy/caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
  db_data:
