version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: legacy72/devops-for-programmers-project-74:latest
    environment:
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: