name: push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v1.2.0
      -
        name: Build prod image
        uses: docker-compose -f docker-compose.yml build app
      -
        name: Run tests
        uses: docker-compose -f docker-compose.yml run app npm ci
      -
        name: Push image to docker hub
        uses: docker-compose -f docker-compose.yml push app:latest